### ISSUE TITLE
Unable to launch Rift due to dependancy issue

### ISSUE THREAD

**Issue by HypeRayy** [ApfelTeeSaft/AllTheLaunchers#2]
When I first opened the program it requested to install some runtimes, which I did, upon opening the menu and pressing "Launch Rift" it comes up with the same issue, even though I have the required dependencies installed.
![image](https://user-images.githubusercontent.com/11124303/164036187-a76fde91-aee8-4b38-b9ca-413cae9ac65f.png)

**Comment by ApfelTeeSaft** [comment]
Rift is bugged in general Running Fortnite Launchers on windows 11 is a bit buggy maybe try and restart your PC
+ install this specific one https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-3.1.411-windows-x64-installer

**Comment by HypeRayy** [comment]
I have already installed the specific DOTNet framework and have restarted my pc already... Should I take this up with Rift's developers?

**Comment by ApfelTeeSaft** [comment]
> I have already installed the specific DOTNet framework and have restarted my pc already... Should I take this up with Rift's developers?

Yeah go in the rift discord that being https://discord.gg/RiftFN

**Comment by ApfelTeeSaft** [comment]
try this https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-3.1.411-windows-x64-installer

**Comment by ApfelTeeSaft** [comment]
wait thats the same

**Comment by HypeRayy** [comment]
<iframe src="https://giphy.com/embed/RfWkZ156KhusgAWFX1" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/latenightseth-seth-meyers-lnsm-RfWkZ156KhusgAWFX1">via GIPHY</a></p>

**Comment by HypeRayy** [comment]
Gave up trying to use Rift. Era worked instantly without the need for extra frameworks to be installed. I am considering this issue closed. Hopefully Rift support will ewventually be fixed.
